# docker login --username=[you account name] crpi-w1ybv4pdc53hqz7r.cn-hangzhou.personal.cr.aliyuncs.com
version: '3'
services:
  # awesome digital human web
  adh_web:
    image: "crpi-w1ybv4pdc53hqz7r.cn-hangzhou.personal.cr.aliyuncs.com/guanping/awesome-digital-human-live2d:adhWeb_2.0.0"
    restart: always
    pull_policy: always
    # network_mode: host
    ports:
      - "3080:3080"
    volumes:
      - ./web/.env:/workspace/.env
  # awesome digital human server
  adh_server:
    image: "crpi-w1ybv4pdc53hqz7r.cn-hangzhou.personal.cr.aliyuncs.com/guanping/awesome-digital-human-live2d:adhServer_2.0.0"
    restart: always
    pull_policy: always
    # network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - ./configs:/workspace/configs
